# Generated by Django 5.0.6 on 2024-07-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waitlist',
            new_name='WaitlistEntry',
        ),
    ]
