# Generated by Django 5.0.6 on 2024-07-03 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0002_rename_waitlist_waitlistentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistentry',
            name='created_at',
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
